config/routes.rb
Rails.application.routes.draw do
  # resources :lions
  resources :lions do
    resources :comments
  end
  root "lions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :lion
end

app/models/lion.rb
class Lion < ApplicationRecord
    has_many :comments
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new
        @comment.user = params[:comment][:user]
        @comment.memo = params[:comment][:memo]
        @comment.lion_id = params[:lion_id]
        @comment.save
        
        redirect_to request.referrer
    end

end

app/controllers/lions_controller.rb
class LionsController < ApplicationController
  before_action :set_lion, only: [:show, :edit, :update, :destroy]

  # GET /lions
  # GET /lions.json
  def index
    @lions = Lion.all
  end

  # GET /lions/1
  # GET /lions/1.json
  def show
  end

  # GET /lions/new
  def new
    @lion = Lion.new
  end

  # GET /lions/1/edit
  def edit
  end

  # POST /lions
  # POST /lions.json
  def create
    @lion = Lion.new(lion_params)

    respond_to do |format|
      if @lion.save
        format.html { redirect_to @lion, notice: 'Lion was successfully created.' }
        format.json { render :show, status: :created, location: @lion }
      else
        format.html { render :new }
        format.json { render json: @lion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lions/1
  # PATCH/PUT /lions/1.json
  def update
    respond_to do |format|
      if @lion.update(lion_params)
        format.html { redirect_to @lion, notice: 'Lion was successfully updated.' }
        format.json { render :show, status: :ok, location: @lion }
      else
        format.html { render :edit }
        format.json { render json: @lion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lions/1
  # DELETE /lions/1.json
  def destroy
    @lion.destroy
    respond_to do |format|
      format.html { redirect_to lions_url, notice: 'Lion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lion
      @lion = Lion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lion_params
      params.require(:lion).permit(:name, :title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lions_helper.rb
module LionsHelper
end

app/views/comments/create.html.erb
<%= @test %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imageupload</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lions/_form.html.erb
<%= form_with(model: lion, local: true) do |form| %>
  <% if lion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lion.errors.count, "error") %> prohibited this lion from being saved:</h2>

      <ul>
      <% lion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, :rows => 10 %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lions/edit.html.erb
<h1>Editing Lion</h1>

<%= render 'form', lion: @lion %>

<%= link_to 'Show', @lion %> |
<%= link_to '뒤로가기', lions_path %>

app/views/lions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lions.each do |lion| %>
      <tr>
        <td><%= lion.name %></td>
        <td><%= lion.title %></td>
        <td><%= lion.content %></td>
        <td><% if lion.image.attached? %>
          YES<%else%>NOT YET
        <% end %>
        <td><%= link_to 'Show', lion %></td>
        <td><%= link_to 'Edit', edit_lion_path(lion) %></td>
        <td><%= link_to 'Destroy', lion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lion', new_lion_path %>

app/views/lions/new.html.erb
<h1>New Lion</h1>

<%= render 'form', lion: @lion %>

<%= link_to '뒤로가기', lions_path %>

app/views/lions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lion.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @lion.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @lion.content %>
</p>
<p>
  <strong>Image:</strong>
  <% if @lion.image.attached? %>
    <%= image_tag(@lion.image, size:'200x200')%>
  <% end %>
</p>

<%= link_to 'Edit', edit_lion_path(@lion) %> |
<%= link_to 'Back', lions_path %>

<%= form_for Comment.new, url:lion_comments_path(@lion.id), method:"POST" do |form| %>
  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


  